name: Deploy via SSH to EC2

on:
  workflow_dispatch:
    inputs:
      port:
        description: "Port to run the container"
        required: true
      domain:
        description: "Domain to configure (optional)"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /usr/local/bin/deploy_helper.sh \
            "${{ github.repository }}" \
            "${{ github.ref_name }}" \
            "${{ github.event.inputs.port }}" \
            "${{ github.event.inputs.domain }}"
